version: '2.1'
services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    volumes:
      - 'mariadb_data:/bitnami'
    environment:
      - MARIADB_USER=bn_wordpress
      - MARIADB_DATABASE=bitnami_wordpress
      - ALLOW_EMPTY_PASSWORD=yes
    healthcheck:
        test: "/opt/bitnami/mariadb/bin/mysql -ubn_wordpress -e 'SHOW DATABASES;'"
        interval: 5s
        retries: 20
  wordpress:
    image: 'wordpress:workshop'
    ports:
      - '80:80'
      - '443:443'
    depends_on:
        mariadb:
            condition: service_healthy
    volumes:
      - ./workshop:/workshop
volumes:
  mariadb_data:
    driver: local
  wordpress_data:
    driver: local
